### ISSUE TITLE
Im trying to join your sever but I'm having trouble.

### ISSUE THREAD

**Issue by jakerankin7** [unstablecraft/Unstablecraft-issues-wiki#2]
Hello, i attempted to join your server in FTB 1.12.2, but when I type in the correct address, a screen pops up that says,"mod rejections....." and many other things. I was looking for a server to play on with my friend since we don't want to have to buy one ourselves.

Thanks for reading

**Comment by DarkPhoenix332** [comment]
Make sure you're running the correct version of the mod pack, which is 1.4.0 beta.

**Comment by unstablecraft** [comment]
will be added to wiki
