### ISSUE TITLE
Screens make me crash

### ISSUE THREAD

**Issue by VliegendeBalzak** [unstablecraft/Unstablecraft-issues-wiki#5]
if you will spawn in/ teleport at my base you will crash becasue screens from opencomputers 

[crash-2018-01-06_21.03.03-client.txt](https://github.com/unstablecraft/Unstablecraft-issues-wiki/files/1609193/crash-2018-01-06_21.03.03-client.txt)

**Comment by unstablecraft** [comment]
the screens will be disabled/Banned

**Comment by unstablecraft** [comment]
this is fixed in the latest update
