### ISSUE TITLE
Rank Upgrades

### ISSUE THREAD

**Issue by TheVampiricT** [unstablecraft/Unstablecraft-issues-wiki#7]
IGN: TheVampiricT
SERVER: FTB Revelations EU 
ISSUE:

Hello Unstablecraft!

This is just a quick thing.
So straight to the point; I want to upgrade my rank from Spartan to Titan, but I feel like I shouldn't have to pay full price when I have part of the rank already. I looked around the Website and couldn't find a spot where I could upgrade my rank from Spartan > Titan. (10$+x$=20$) what I want to pay is X, the difference between the two ranks. 

- I bought Spartan yesterday (January 12, 2018)

Sorry if my wording is absolutely terrible, but hopefully you get what I mean.

Thank you so much for your time!
Thomas Steele (TheVampiricT)
Spartan on UnstableCraft Revelations EU Server

**Comment by unstablecraft** [comment]
the rank upgrade are a thing on my todo list ill @ you when ive done it

**Comment by unstablecraft** [comment]
@TheVampiricT  upgrades where Added 


-Fixed
